### ISSUE TITLE
Improve dev experience using exposed_method without any params

### ISSUE THREAD

**Issue by petrus-v** [AnyBlok/anyblok_furetui#37]
Not sure what's the abious solution to fix that.

While exposing a class method without any params like this:

```python
    @exposed_method()
    def generate_bl(cls, authenticated_userid=None):
```

obviously this should be::

```python
    @exposed_method(authenticated_userid="authenticated_userid")
    def generate_bl(cls, authenticated_userid=None):
```

I got the following error:
```log
Traceback (most recent call last):
  File "/home/pverkest/.pyenv/versions/3.7.3/envs/optics/lib/python3.7/site-packages/anyblok_pyramid_rest_api/crud_resource.py", line 35, in saved_errors_in_request
    yield
  File "/home/pverkest/anybox/clients/sensee/logistic-central-optics/libs/AnyBlok_FuretUI/anyblok_furetui/furetui/furetui.py", line 198, in call_exposed_method
    res = getattr(obj, call)(**options, **data)
TypeError: generate_bl() argument after ** must be a mapping, not NoneType
```
I wondering if it's a good idea in case of data is None to instantiate an empty dict to avoid this traceback but the matter is that we do note notice developer that he missed something...

**Comment by petrus-v** [comment]
pris en charge dans #41
